[project]
name = "passive-extended-matchgate-simulator"
version = "0.1.0"
description = "Passive extended matchgate quantum circuit simulator"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "numpy>=1.25",
  "scipy",
  "qiskit",
]

[build-system]
requires = [
  "setuptools>=61.0",
  "wheel",
  "setuptools-rust>=1.5.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools-rust]
rust_extensions = [
  { path = "rust_backend/Cargo.toml", binding = "pyo3", debug = false },
]
strip = "auto"

[tool.ruff]
src = ["python"]
include = [
  "pyproject.toml",
  "python/**/*.py",
  "python/**/*.pyi",
  "tests/**/*.py",
  "tests/**/*.pyi",
  "docs/**/*.py",
  "docs/**/*.pyi",
  "docs/**/*.ipynb",
]

[tool.ruff.lint]
select = ["E", "F", "I", "N", "NPY", "NPY201"]
