[project]
name = "passive-extended-matchgate-simulator"
version = "0.1.0"
description = "Passive extended matchgate quantum circuit simulator"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "numpy>=1.25",     # for your Python‐side arrays & wrappers
]

[build-system]
requires = ["maturin>=1.2"] 
build-backend = "maturin"

[tool.maturin]
bindings = "pyo3"     # tells maturin you’re using PyO3
